version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: store
      MYSQL_USER: kg
      MYSQL_PASSWORD: kgpass
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - rabbitmq
    ports:
      - "8080:8080"